# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.home=C:\\Users\\Larus\\AppData\\Local\\Programs\\Microsoft\\jdk-25.0.2.10-hotspot

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.1.0
maven_group=com.pixelpanel
archives_base_name=pixelpanel

# Dependencies
fabric_api_version=0.152.2+26.2
